version: '3'

services:
  influx:
    image: influxdb
    ports:
      - "8086:8086"
  timescale:
    image: timescale/timescaledb
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
 
